### ISSUE TITLE
API Rewriting

### ISSUE THREAD

**Issue by dgomesbr** [brsanthu/google-analytics-java#17]
Hey @brsanthu, I've been using your API for a while but the design of it keeps bothering me, I'd like to know if you're interested in pushing a redesign of it on a Fluent interface way, so instead of:

```
GoogleAnalytics ga = new GoogleAnalytics("UA-12345678-1");
ga.post(new PageViewHit("https://www.google.com", "Google Search"));
```

We would have: 

```
GoogleAnalytics ga = GoogleAnalyticsBuilder.withUA("UA-12345678-1").build();
ga.trackPageView("https://www.google.com", "Google Search").post();
```

Or

```
GoogleAnalytics ga = GoogleAnalyticsBuilder.withUA("UA-12345678-1").build();
ga.trackPageView("https://www.google.com", "Google Search").postAsync();
```

Or

```
GoogleAnalytics ga = GoogleAnalyticsBuilder.withUA("UA-12345678-1").build();
ga.trackPageView("https://www.google.com", "Google Search").withRequestProvider(new RequestProvider() {
    public GoogleAnalyticsRequest getRequest() {
        return new PageViewHit("https://www.google.com", "Google Search");
    }
}).postAsync();
```

Would you like to talk about it?

**Comment by akoscz** [comment]
@dgomesbr if you're still interested in a GoogleAnalytics library, I started up a new project the other day. https://github.com/akoscz/GoogleAnalytics
My goal was to write as little code as necessary to get a simple GoogleAnalytics Measurement Protocol implementation going.  I welcome feedback and/or contributions from anyone who's interested in the project.

**Comment by brsanthu** [comment]
Proposed api changes have been incorporated into upcoming 2.0.0. Please check out 2.0.0 branch. Any feedback is welcome. I promise, it will not be another 3 years :)

**Comment by brsanthu** [comment]
New api has been adopted in 2.0.0 branch which is based on Java8. Here are some examples.

To Create Instance:
```
ga = GoogleAnalytics.builder().withDefaultRequest(req).withConfig(config).withTrackingId(trackingId).build();
```
To Post requests:
 
```
 ga.event().eventCategory("Commands").eventAction(cmdId).eventLabel(cmdName).eventValue(success ? 1 : 0).postAsync()
```
or 

```
ga.event().eventCategory("Commands").eventAction(cmdId).eventLabel(cmdName).eventValue(success ? 1 : 0).post()
```
