### ISSUE TITLE
post and postAsync methods

### ISSUE THREAD

**Issue by nofaruccio** [brsanthu/google-analytics-java#19]
Hi,
very nice work!!!!!!
I've some customized dimensions and I'm sending "post()" and "postAsync()" methods to GoogleAnalytics.
Now, the impression is that not all sends arrive to GA. Many sends get lost.
Why?
Is it possible?
May you help me?
Thanks for all.
Onofrio

I'm using this code:

GoogleAnalytics ga = new GoogleAnalytics("UA-12345678-1");
PageViewHit request = new PageViewHit("http://customurl.com", "Search");
request.customDimention(1, "first-column, 11-13(1)");
request.customDimention(2, "second-column, 11-13(2)");
request.customDimention(3, "third column, 11-13(3)");
ga.post(request);

OR

GoogleAnalytics ga = new GoogleAnalytics("UA-12345678-1");
PageViewHit request = new PageViewHit("http://customurl.com", "Search");
request.customDimention(1, "first-column, 11-13(1)");
request.customDimention(2, "second-column, 11-13(2)");
request.customDimention(3, "third column, 11-13(3)");
ga.postAsync(request);

OR

ga.postAsync(new RequestProvider() {
        public GoogleAnalyticsRequest getRequest() {
                PageViewHit request = new PageViewHit("http://customurl.com", Search");
            request.customDimention(1, "prima-colonna-nunc, 11-13(1)");
            request.customDimention(2, "seconda-colonna-nunc, 11-13(2)");
            request.customDimention(3, "terza-colonna-nunc, 11-13(3)");
                return request;
            }
        });

**Comment by brsanthu** [comment]
Due to how backup queue was configured, it was possible that some events got dropped if queue was way bigger. This default has been changed to post the event in thread view instead of dropping the event.

This is part of upcoming 2.0.0
