### ISSUE TITLE
Need example to use GA

### ISSUE THREAD

**Issue by tranthanhhieu3000** [brsanthu/google-analytics-java#20]
Hi  brsanthu,

I'm very new with GA and I found this resource. I got it into my local and can build with Netbean (it take 2 hours for netbean downloaded all jar files). But now I don't know how to use for get data or post data to GA. Can you give me some url that link to example code (sorry for my basic request).

Thanks.

**Comment by eduardommello** [comment]
+1

**Comment by edbras** [comment]
+1

**Comment by brsanthu** [comment]
Wiki will be updated with an example as part of upcoming 2.0.0 release
