### ISSUE TITLE
Running on App Engine

### ISSUE THREAD

**Issue by cilogi** [brsanthu/google-analytics-java#21]
I'm using this library on App Engine.  The implementation in `GoogleAnalytics.java` doesn't work on App Engine as (a) you can't use threading and (b) you have to use the URL service which doesn't work out of the box with the Apache components.

I've rewritten `GoogleAnalytics.java` (code [here](https://gist.github.com/cilogi/142fa68ea89de2214073)) but for it to work the visibility of some methods needs to change.  Specifically, `getUrl` in `GoogleAnalyticsConfig.java`, and the `*Hit` methods in `GoogleAnalyticsStats.java`.  

If you're interested I'll create a pull request.

**Comment by tj-recess** [comment]
+1. I need this as well. @cilogi: Could you share or merge your working code?

**Comment by brsanthu** [comment]
If you are still interested, I have started working on 2.0.0 version based on 1.8. Do you want to share some thoughts on how to make this work on app engine?
