### ISSUE TITLE
GA Feature "exclude bot traffic" filters out events

### ISSUE THREAD

**Issue by phammer** [brsanthu/google-analytics-java#22]
The feature "exclude bot traffic" of Google Analytics filters out the GA events posted from the server via the google-analytics-java plugin (v1.1.1). Our application is deployed on Heroku and based on Play.

Any idea how to solve this? Did we miss to configure the plugin correctly / passing the right parameters to GA in the event posts?

**Comment by glasscubes** [comment]
We have the same issue

**Comment by dgomesbr** [comment]
@phammer and @glasscubes filter out the user-agent, it should be the same as your client (instead of for example Jakart HTTP.
