### ISSUE TITLE
Custom dimension aren't being delivered with the event hit

### ISSUE THREAD

**Issue by maxkremer** [brsanthu/google-analytics-java#24]
I'm trying to use the `customDimention(int index, String value)` method of `EventHit` and the custom dimensions are not being delivered to google analytics. The event comes through but no custom dimension data.

I verified that I can send custom dimensions with the google's native JS api.

**Comment by mizerlou** [comment]
@maxkremer, did you ever figure this out?

**Comment by maxkremer** [comment]
@mizerlou ya it was simply the fact that it takes a while (sometimes hours) before stuff appears in GA. You also have to ensure that you set up the dimensions correctly. Closing the issue since everything works fine. Thanks for the reminder ;)
