### ISSUE TITLE
Add IDE specific files to .gitignore

### ISSUE THREAD

**Issue by dgomesbr** [brsanthu/google-analytics-java#29]
Eclipse project files are committed in the repo.

```
.classpath
.project
.settings/org.eclipse.jdt.core.prefs
```

**Comment by brsanthu** [comment]
Incorporated into upcoming 2.0.0 version.

**Comment by dgomesbr** [comment]
Yay, you're back



Att,

Diego Magalhães

*http://diegomagalhaes.com <http://diegomagalhaes.com>**claro @ +55 11
99234 8953*

**Comment by brsanthu** [comment]
Yes, albeit after 3 years :)
