### ISSUE TITLE
ThreadExecutor uses an unbounded queue and will create an OOM with high throughput usage

### ISSUE THREAD

**Issue by dgomesbr** [brsanthu/google-analytics-java#31]
The code for the GoogleAnalytics.java will create an Unbounded `LinkedBlockingDeque<Runnable>()` with an _five minutes_ timeout for each call and a default `0` to `config.getMaxThreads` poolSize.

``` java
protected synchronized ThreadPoolExecutor createExecutor(GoogleAnalyticsConfig config) {
   return new ThreadPoolExecutor(0, config.getMaxThreads(), 5, TimeUnit.MINUTES, new LinkedBlockingDeque<Runnable>(), createThreadFactory());
}
```

We should at least make that configurable with sensible defaults. It also uses the wrong constructor with the defaultHandler which is `private static final RejectedExecutionHandler defaultHandler = new AbortPolicy();` and will cause events to be descarded.

**Comment by brsanthu** [comment]
You proposed PR changes are incorporated into upcoming 2.0.0 version
