### ISSUE TITLE
Separate infra code from client exposed code

### ISSUE THREAD

**Issue by bluephoton** [brsanthu/google-analytics-java#41]
Couldn't see help here so looked at the code, I think things that I'll use should be in separate namespace/directory (like Ga, GaConfig, different request types...etc)

**Comment by brsanthu** [comment]
Hi, currently working on 2.0.0 based on Java 1.8. What suggestions you have on package restructure?

**Comment by brsanthu** [comment]
Check out the 2.0.0 branch which has new package structure and makes use interface. Please check out and provide any feedback.

**Comment by brsanthu** [comment]
Closing this issue. If there is any suggestion, please create new issue with feedback.

**Comment by bluephoton** [comment]
Wasn't able to comment earlier (looks like there is issue with chrome, using edge now):

Looks great! Thanks for updating!
My only feedback is to get rid of slf4j, perhaps I can pass ILogProvider and choose how to log. I created issue #42 for this.

Also if there is a light weight alternative to Apache http client will be better. Apache http client and core bring lots of dependency and since I'm obfuscating my jar, it took me very long time to fix related proguard issues and I'm still not done!

**Comment by brsanthu** [comment]
In version 2.0.0, httpclient has been abstracted using few interfaces with apache being the default client. If you don't want to deal with apache httpclient, you can exclude that dependency, provide your own implementation of `HttpClient`. For ex.,

```
ga = GoogleAnalytics.builder().withHttpClient(new YourOwnHttpClient()).build()
```

**Comment by bluephoton** [comment]
I'm not familiar with slf4j but ideally I don't want my project to be aware of it, I had to add its jars among other things to get a clean run and obfuscate with no issue.

Great addition abstracting http client, I'll try to follow your suggestion if if couldn't fix my progaurd issues today.
