### ISSUE TITLE
Is there any documentation for v2?

### ISSUE THREAD

**Issue by spyrosel** [brsanthu/google-analytics-java#46]
I can't find anything like this https://github.com/brsanthu/google-analytics-java/wiki/V1-Readme one for v1. Everything is changed and I can't work it out. Could you give me a basic example of the client initialization, a page view hit and an event hit?

**Comment by brsanthu** [comment]
Updated the readme in master branch for 2.x version. Please check it out and let me know if something needs to be updated.
