### ISSUE TITLE
How to set country and city 

### ISSUE THREAD

**Issue by rinkygupta2008** [brsanthu/google-analytics-java#47]
i am not able to set country code and city.

How to set country and city through brsanthu/googleanalytics API

  GoogleAnalyticsConfig config = new GoogleAnalyticsConfig();
        config.setDiscoverRequestParameters(true);
        config.setEnabled(true);
            
        if(sGoogleAnalytics == null) sGoogleAnalytics = new GoogleAnalytics(config, ID, APP_NAME, VER);

**Comment by brsanthu** [comment]
You need to use geoId parameter to set country or city. To get the geoId for city, check out https://developers.google.com/analytics/devguides/collection/protocol/v1/geoid

**Comment by rinkygupta2008** [comment]
how to set geoID and in which method.
If you can give some example or link that will be helpful to use this API

**Comment by brsanthu** [comment]
Here is an example

```
    ga.pageView()
        .documentTitle('title')
        .documentPath("/url")
        .clientId("Some Id")
        .userIp("198.165.0.1")
        .geoid("US")
        .send();        
```

**Comment by rinkygupta2008** [comment]
1. i am using 1.0.0 API
2. 2.0.0 api i am not able to use

not able to test this java file 
https://github.com/brsanthu/google-analytics-java/blob/master/src/test/java/com/brsanthu/googleanalytics/GoogleAnalyticsTest.java

` ga = GoogleAnalytics.**builder()**.withTrackingId("").withAppName("Junit Test").withAppVersion("1.0.0").build();`


.builder() is showing error.

**Comment by brsanthu** [comment]
That example doesn't work with 1.x builds as API went through major refactoring in 2.x. 

Geoid parameter is added only in 2.x branch. If you cannot use 2.x branch, but still want to add to 1.x branch, if you send a PR with change, I can merge and release new 1.x build with that parameter.

**Comment by rinkygupta2008** [comment]
I want to set country with google analytics.
I can use 2.0 API also. I have imported 2.0 api through maven, but when i am calling GoogleAnalytics.builder() its showing error.

where i can find documentation for 2.0 api ?

**Comment by brsanthu** [comment]
Documentation is there in the main page. Here is the complete example of sending geo id. 

```
package com.brsanthu.gatest;

public class GaTest {
    public static void main(String[] args) {

        GoogleAnalytics ga = GoogleAnalytics.builder().withTrackingId("UA-00000000").build();

        ga.pageView()
            .documentTitle("GaTest")
            .documentPath("/home")
            .userIp("198.165.0.1")
            .geoid("US")
            .send();
    }
}
```

**Comment by rinkygupta2008** [comment]
![image](https://user-images.githubusercontent.com/11532281/36408102-239c6e1c-1629-11e8-871c-c0c01dd5006f.png)

**Comment by rinkygupta2008** [comment]
JAVA :  JRE 1.8.0
google analytics maven dependency :
<dependency>
    <groupId>com.brsanthu</groupId>
    <artifactId>google-analytics-java</artifactId>
    <version>2.0.0</version>
</dependency>


what need to do to access builder() static method of GoogleAnalytics

**Comment by rinkygupta2008** [comment]
Thank you for fast responses .
In compare to 1.x library 2.x library is bit slow. uploaded data is inconsistent. I will test more.

For geoid , is there any method which will automatically set country. because from java when i am calling **user.country** its returning **US** but i am in **india**.

getting location through IP address is not working for all IP address.

**Comment by brsanthu** [comment]
> In compare to 1.x library 2.x library is bit slow. uploaded data is inconsistent. I will test more.
Please create an issue if you see any inconsistencies. I don't see any reason why 2.x will be slower than 1.x as it is mere api refactoring with underlaying mechanisms are same.

Except if you are using batching, in that case requests will not be sent immediately but only as a batch after configured number of events are submitted.

> For geoid , is there any method which will automatically set country. because from java when i am calling user.country its returning US but i am in india.

I don't recall why would it return US while you are in India, unless you are running this code via vpn connected service or via a server which is hosted in US. Either way, it is upto consumer of the library to determine the appropriate value.

> getting location through IP address is not working for all IP address.

Yes, getting country through IP may not be reliables all the times.
